FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

COPY crypto_watcher /app/crypto_watcher

CMD ["poetry", "run", "crypto-watcher"]